services:
  n8n:
    image: n8nio/n8n:latest   
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - DB_POSTGRESDB_SSL_ENABLED=${DB_POSTGRESDB_SSL_ENABLED}
      - DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
      #- N8N_EXECUTIONS_PROCESS=main 
      #- N8N_COOKIES_SAMESITE=lax    
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      #- N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      #- N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      #- N8N_PROTOCOL=http
      #- WEBHOOK_URL=http://${N8N_HOST:-localhost}:5678/
      #- GENERIC_TIMEZONE=Europe/Paris
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      #- EXECUTIONS_DATA_SAVE_ON_SUCCESS=none
      #- EXECUTIONS_DATA_SAVE_ON_ERROR=all
      #- EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS=true
      #- EXECUTIONS_DATA_PRUNE=true
      #- EXECUTIONS_DATA_MAX_AGE=168

    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/workflows
    
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${N8N_PORT:-5678}/healthz || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5

  bootstrap:
    image: oven/bun:1.1-alpine
    container_name: n8n-bootstrap
    working_dir: /app
    volumes:
      - .:/app  # Monte la racine (contient package.json)
    env_file:
      - .env
    # On utilise 'bun install' (tout court) pour installer ce qui est dans package.json 
    # ET on lance le bon fichier 'bootstrap/http.js'
    command: >
      sh -c "bun install && bun bootstrap/bootstrap.js"
    depends_on:
      n8n:
        condition: service_healthy
    restart: "no"
volumes:
  n8n_data:
    driver: local
